### ISSUE TITLE
Failing test message and stack trace not showing

### ISSUE THREAD

**Issue by Jonathan-Turner** [im-open/process-dotnet-test-results#38]
Good morning. I have been playing with your action in a small test project I am working on and ran into an issue I cannot see documented / commented on anywhere in the notes.

With this configuration (mostly copied from your readme), it is effectively reporting on error count, but it is not displaying details for failing tests.

```
    - name: dotnet test
      run: dotnet test --logger trx --configuration Release

    - name: Process trx reports with default
      if: always()
      # You may also reference just the major or major.minor version
      uses: im-open/process-dotnet-test-results@v3.0.0
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}      
        create-status-check: true
        create-pr-comment: true
        update-comment-if-one-exists: true
        timezone: 'america/chicago'
        comment-identifier: 'BookQuest PR Test Output'

    - name: Annotate Test Outcome
      if: steps.process-trx.outputs.test-results-truncated == 'true'
      run: cat ${{ steps.process-trx.outputs.test-results-file-path }} > $GITHUB_STEP_SUMMARY
```

![image](https://github.com/im-open/process-dotnet-test-results/assets/6035179/5d9b9fb5-0752-4e29-bc63-b269675e4170)

If I have made a mistake in configuration / missed something, my apologies. Otherwise, there might be an issue with assigning / showing these values.

Appreciate any help!

**Comment by simonegli8** [comment]
Did you solve this? I have the same issue. My yaml:

```
    - name: Run Unit Tests
      working-directory: SolidCP\Sources
      continue-on-error: true
      run: |
        dotnet test SolidCP.Tests.sln -v n --logger trx --configuration Release --results-directory ..\..\test-results

    - name: Publish Unit Tests
      id: process-trx
      uses: im-open/process-dotnet-test-results@v3.0.1
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        base-directory: './test-results'
        create-status-check: true
        create-pr-comment: true
        update-comment-if-one-exists: true
        ignore-test-failures: true
        timezone: 'europe/zurich'
        comment-identifier: 'bff-tests'
```
